### ISSUE TITLE
[Bug] Forge OpenCL examples quit with segmentation fault

### ISSUE THREAD

**Issue by 3togo** [arrayfire/forge#243]
It is compiled using ubuntu 23.04, cuda 12.1, nvidia 530.30.02

Below is the backtrace:

```
Thread 1 "plot3_opencl" received signal SIGSEGV, Segmentation fault.
0x00007ffff7161107 in _XSend () from /lib/x86_64-linux-gnu/libX11.so.6
(gdb) bt
#0  0x00007ffff7161107 in _XSend () from /lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007ffff7159bb5 in XQueryExtension () from /lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff714db26 in XInitExtension () from /lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff6742821 in XextAddDisplay () from /lib/x86_64-linux-gnu/libXext.so.6
#4  0x00007ffff5d5485d in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#5  0x00007ffff5d2c8b5 in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#6  0x00007ffff5d2d5d3 in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#7  0x00007ffff434540c in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.530.30.02
#8  0x00007ffff436d1a7 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.530.30.02
#9  0x00007ffff4343413 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.530.30.02
#10 0x00007fffef8dbe86 in ?? () from /lib/x86_64-linux-gnu/libnvidia-opencl.so.1
#11 0x000055555555b7d5 in cl::Context::~Context() ()
#12 0x00007ffff743ebe5 in __run_exit_handlers (status=0, listp=0x7ffff75f6840 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:111
#13 0x00007ffff743ed20 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:141
#14 0x00007ffff7423a97 in __libc_start_call_main (main=main@entry=0x5555555589a0 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffd788)
    at ../sysdeps/nptl/libc_start_call_main.h:74
#15 0x00007ffff7423b49 in __libc_start_main_impl (main=0x5555555589a0 <main>, argc=1, argv=0x7fffffffd788, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffd778) at ../csu/libc-start.c:360
#16 0x00005555555597b5 in _start ()
```

**Comment by 3togo** [comment]
reinitialize context to empty after releaseGLBuffer(handle) could fix the problem.

 ```
releaseGLBuffer(handle);
  context = cl::Context();
```
